Repository UMLCloudComputing/UniPath.io, pull requests merged in 2024-01, with the labels that each got.

#72 added JSDoc to Base Layout file
  src/app/layout.js
Labels: documentation

#73 Added JSDoc for landing page
  src/app/(landing)/page.js
Labels: documentation

#75 Added JSDoc to Components in home
  src/app/(home)/AppBar.js
  src/app/(home)/BottomNavigation.js
  src/app/(home)/Dialog.js
  src/app/(home)/Drawer.js
  src/app/(home)/layout.js
Labels: documentation

#77 Logout button added
  src/app/(home)/AppBar.js
Labels: Front End

#90 Implemented more the Tasks page groundwork (UI, working wireframe, etc)
  .gitignore
  amplify/.config/project-config.json
  amplify/README.md
  amplify/auth/resource.ts
  amplify/backend.ts
  amplify/cli.json
  amplify/data/resource.ts
  amplify/hooks/README.md
  amplify/package.json
  amplify/team-provider-info.json
  amplify/tsconfig.json
  package-lock.json
  package.json
  src/app/(home)/AppBar.js
  src/app/(home)/tasks/Column.js
  src/app/(home)/tasks/initialData.js
  src/app/(home)/tasks/page.js
Labels: Ready for review, Front End

#92 Implemented more the Tasks page groundwork (UI, working wireframe, etc) (Round 2)
  .gitignore
  amplify/.config/project-config.json
  amplify/README.md
  amplify/auth/resource.ts
  amplify/backend.ts
  amplify/cli.json
  amplify/data/resource.ts
  amplify/hooks/README.md
  amplify/package.json
  amplify/team-provider-info.json
  amplify/tsconfig.json
  jsconfig.json
  package-lock.json
  package.json
  src/app/(home)/AppBar.js
  src/app/(home)/tasks/Column.js
  src/app/(home)/tasks/initialData.js
  src/app/(home)/tasks/page.js
  src/app/layout.js
  src/components/ConfigureAmplify.js
Labels: Ready for review, Front End
